// import { getUserInfo } from '@/services/service';
import type { Settings as LayoutSettings } from '@ant-design/pro-layout';
import { PageLoading } from '@ant-design/pro-layout';
import { message, notification } from 'antd';
import React from 'react';
import type { RequestConfig } from 'umi';
import type { ResponseError } from 'umi-request';
try {
  // @ts-ignore
  isGrayAllPage(isPublic); // 哀悼模式 isPublic为config文件里定义的变量
} catch (error) {
  console.log('哀悼模式 执行错误', error);
}

/**
 * 获取用户信息比较慢的时候会展示一个 loading
 */
export const initialStateConfig = {
  loading: <PageLoading />,
};

export async function getInitialState(): Promise<{
  userName?: string;
  userNo?: string;
  realName?: string;
  operator?: string;
  settings?: Partial<LayoutSettings>;
  tabLayoutType?: any;
  compareIndexes?: string[];
  [key: string]: any;
}> {
  // TODO 获取用户信息
  const { data } = {
    "data": {
        "aclvoList": null,
        "appPrivilegeValueVOS": null,
        "application": "f",
        "applicationGroupVOS": [
            {
                "application": "fundportal",
                "createTime": 1650441282000,
                "creator": null,
                "delFlag": 1,
                "id": "047dc7a00982e4c2fdc6258553339d1d",
                "keyword": null,
                "name": "产品全景图展示最新持仓数据权限",
                "note": null,
                "sn": "show_newest_market_auth",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1669104299000,
                "creator": null,
                "delFlag": 1,
                "id": "0a4043edc85b4d06727149c6bc6ababa",
                "keyword": null,
                "name": "资讯模块权限组",
                "note": null,
                "sn": "information_module_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1652663030000,
                "creator": null,
                "delFlag": 1,
                "id": "10d6fc227cc87281bde546fd4f34a612",
                "keyword": null,
                "name": "风险控制",
                "note": "风险控制角色",
                "sn": "riskControl",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1657673678000,
                "creator": null,
                "delFlag": 1,
                "id": "1774abd7d3d4c305d0540fdfedf638e7",
                "keyword": null,
                "name": "基金运营部",
                "note": null,
                "sn": "fund_running_dept",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1656488060000,
                "creator": null,
                "delFlag": 1,
                "id": "17ae47599afd929d4d13d4fb3e67a414",
                "keyword": null,
                "name": "直销CRM-理财顾问",
                "note": "用于直销CRM使用",
                "sn": "zx_crm_advisor",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1638492580000,
                "creator": null,
                "delFlag": 1,
                "id": "1c59d59ec06584098e80fff32e5abf62",
                "keyword": null,
                "name": "产品资产组合组",
                "note": "保存资产组合功能角色",
                "sn": "PROT_FO_LIO",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1662514765000,
                "creator": null,
                "delFlag": 1,
                "id": "2570011b6862d95be64a11dd1df09e46",
                "keyword": null,
                "name": "宣推数据组",
                "note": "控制\n公司持有人：'_production_FundCompany__Menu___Holder'\n公司获奖：'_production_FundCompany__Menu___authAward'\n基金宣推数据：'_production_IndexDetail__Menu___Promote'",
                "sn": "promotion_data_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1635142540000,
                "creator": null,
                "delFlag": 1,
                "id": "2a2890cf124704a6ed299831845843ad",
                "keyword": null,
                "name": "资讯组",
                "note": null,
                "sn": "InfoGroup",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1635472726000,
                "creator": null,
                "delFlag": 1,
                "id": "2c7b71ca8b054fb67e06697fcd980198",
                "keyword": null,
                "name": "销售组",
                "note": null,
                "sn": "SalesGroup",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1646875970000,
                "creator": null,
                "delFlag": 1,
                "id": "39d8726a48770db42f8d84235fada0d8",
                "keyword": null,
                "name": "行业证券分类体系管理组",
                "note": null,
                "sn": "securities_sort_manager",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1656488224000,
                "creator": null,
                "delFlag": 1,
                "id": "40d107e1a6925f8c713bf8be49396c73",
                "keyword": null,
                "name": "直销CRM-审计员",
                "note": "用于直销CRM审计",
                "sn": "zx_crm_audit",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1647399956000,
                "creator": null,
                "delFlag": 1,
                "id": "48461819b3c0cbe9ec8289fb54e4df8c",
                "keyword": null,
                "name": "股票投资研究域",
                "note": "模拟组合 - 股票投资研究域",
                "sn": "mp_stock_ir_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1647400007000,
                "creator": null,
                "delFlag": 1,
                "id": "5464759224d5c80cf5d6b9462bd7c2ac",
                "keyword": null,
                "name": "投研开发测试域",
                "note": "模拟组合 - 投研开发测试域",
                "sn": "mp_it_test_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1657004877000,
                "creator": null,
                "delFlag": 1,
                "id": "6fdf2bb46e4bee34659fd38e6106792f",
                "keyword": null,
                "name": "销售VOG看板-测试用",
                "note": "VOG专用组，只针对特定人群，禁止随意添加！！！",
                "sn": "salesVogBoard",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1652147580000,
                "creator": null,
                "delFlag": 1,
                "id": "74c51cf8c979f098e8c2df235d41096e",
                "keyword": null,
                "name": "销售配置管理组",
                "note": null,
                "sn": "sales_config_manager",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1645064726000,
                "creator": null,
                "delFlag": 1,
                "id": "74ca14615a85842ba60febd6bbf0d2d6",
                "keyword": null,
                "name": "产品经理",
                "note": null,
                "sn": "productManager",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1659674254000,
                "creator": null,
                "delFlag": 1,
                "id": "77ca593226d7649c80105d13e7c2fdaa",
                "keyword": null,
                "name": "投资组系统管理员",
                "note": null,
                "sn": "investment_system_admin",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1671787412000,
                "creator": null,
                "delFlag": 1,
                "id": "82fc6dbaecf559d691d48b1d0fef49b8",
                "keyword": null,
                "name": "尾佣配置管理员组",
                "note": null,
                "sn": "care_fee_config_admin_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1640140912000,
                "creator": null,
                "delFlag": 1,
                "id": "8b8b734bab625456af04f828e051f62e",
                "keyword": null,
                "name": "产品组",
                "note": null,
                "sn": "ProductGroup",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1634534016000,
                "creator": null,
                "delFlag": 1,
                "id": "917cabebce60aada2e08328c9ae8330c",
                "keyword": null,
                "name": "初始化组",
                "note": null,
                "sn": "INITIAL_USER_GROUP",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1667209545000,
                "creator": null,
                "delFlag": 1,
                "id": "a15108d21e47b558c6be3187ed3d1dd1",
                "keyword": null,
                "name": "scrm使用人员",
                "note": "移动端",
                "sn": "SCRM",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1656488039000,
                "creator": null,
                "delFlag": 1,
                "id": "b70506f8ff7214479906c23c1be50da2",
                "keyword": null,
                "name": "直销CRM-管理员",
                "note": "用于直销CRM配置管理",
                "sn": "zx_crm_admin",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1663220548000,
                "creator": null,
                "delFlag": 1,
                "id": "c8eb3dbd057ca31b87ba86d9b7d4ed2f",
                "keyword": null,
                "name": "投资风控脚本管理组",
                "note": null,
                "sn": "investment_script_management_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1640759933000,
                "creator": null,
                "delFlag": 1,
                "id": "d8e3f9ca00ddc074491c9ad5c55fe8be",
                "keyword": null,
                "name": "全产品权限",
                "note": "用于咨询模块, 表示拥有所有产品的访问权限",
                "sn": "allProd",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1663901411000,
                "creator": null,
                "delFlag": 1,
                "id": "dd4c3d997f800d8d3d97fdf6b82499b0",
                "keyword": null,
                "name": "销售-理财师后台管理-全部权限",
                "note": "销售-理财师后台管理-全部页面",
                "sn": "fundsalesmrksupport",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1669855935000,
                "creator": null,
                "delFlag": 1,
                "id": "e4ef1f069ab2533800b896b24867828a",
                "keyword": null,
                "name": "开户行管理权限组",
                "note": null,
                "sn": "message_manage_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1670226732000,
                "creator": null,
                "delFlag": 1,
                "id": "f219b2dba128c86fe11a6ba41cd38d17",
                "keyword": null,
                "name": "基金索引列项筛选权限group",
                "note": null,
                "sn": "fund_index_group",
                "updateTime": null,
                "updator": null,
                "validState": 1
            },
            {
                "application": "fundportal",
                "createTime": 1669713695000,
                "creator": null,
                "delFlag": 1,
                "id": "faa8446f36c28fe152176af00f7aec5c",
                "keyword": null,
                "name": "产业链模块权限组",
                "note": null,
                "sn": "industrialChainGroup",
                "updateTime": null,
                "updator": null,
                "validState": 1
            }
        ],
        "createTime": 1653470548000,
        "creator": null,
        "delFlag": 1,
        "dingTalkAvater": "",
        "dingTalkDeptId": 1,
        "dingTalkUserId": "1739620163672387",
        "ecologyOaUserId": null,
        "extraDatas": {},
        "id": "e0839fd03b71281375af3759c4076814",
        "keyword": null,
        "leaderUserRealname": null,
        "leaderUsername": null,
        "moduleVOS": [
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "04c388ffdca99c3a0373d635a9aed73f",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "机构服务静态资源配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_staticResource",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_staticResource"
            },
            {
                "component": "home",
                "createTime": 1664287552000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "11dc9625c6562fb9f1ff1d2ab16abcfb",
                "image": "ant-design:home-twotone",
                "keyword": null,
                "moduleType": 0,
                "name": "移动SCRM首页(勿删)",
                "orderNo": null,
                "parentModule": null,
                "pid": null,
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_home",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "19298c8ade1b87c4a744b5f4dda5dc81",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "客户经理配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_clientManager",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_clientManager"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "1c047891393112782721f2771dc74dff",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "大盘显示类型配置页面",
                "orderNo": null,
                "parentModule": null,
                "pid": "a431b482cd7f0a1c36a150382230be3b",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_panel",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_panel"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "246fef36ba531a5b0fefb32584cfaf21",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "荣誉堂后台配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "a431b482cd7f0a1c36a150382230be3b",
                "showStatus": 1,
                "sn": "_marketing_honorHall",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_honorHall"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "25bd5f5f50990bac3df8a67557caaa05",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "基金细节",
                "orderNo": null,
                "parentModule": null,
                "pid": "c90481c08033f40d1338db706e2af50a",
                "showStatus": 1,
                "sn": "/production/IndexDetail",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/IndexDetail"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "26d4210f79a49b9e70aa9c6cab20caa5",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "产业链设置",
                "orderNo": null,
                "parentModule": null,
                "pid": "ba9bad34d77e05a12d22ca66fe9af23e",
                "showStatus": 1,
                "sn": "/industrialChain/set",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/industrialChain/set"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "2ae999ece8c5160b476d33f0371bc3f9",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "尾佣管理",
                "orderNo": null,
                "parentModule": null,
                "pid": "f813036a04478603f4e30019e71d3823",
                "showStatus": 1,
                "sn": "/production/businessManage/trailingCommission",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/businessManage/trailingCommission"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "302cb20d253e7992b5bf8ba8423039a2",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "指数使用费",
                "orderNo": null,
                "parentModule": null,
                "pid": "c90481c08033f40d1338db706e2af50a",
                "showStatus": 1,
                "sn": "indexFee",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/indexFee"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "3481c128c970b9b1a508e20b432ecc87",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "机构服务文案配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_copywriter",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_copywriter"
            },
            {
                "component": "page",
                "createTime": 1652148946000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "373d3eb6061b3f3e89b0c88c905d1310",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "权限配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_authority",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_authority"
            },
            {
                "component": "menu",
                "createTime": 1656488085000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "39035fe22e4e75cafdcc7c21d92636f2",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "直销CRM",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM"
            },
            {
                "component": "element",
                "createTime": 1650441082000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "39de155fb0701545bb950c5a27eacb98",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "持仓信息五大债券时间信息",
                "orderNo": null,
                "parentModule": null,
                "pid": "d4d7a66aa11d9c994c56cf62ef0a06f3",
                "showStatus": 1,
                "sn": "_production_index_detail__bondPosition___datePicker",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_index_detail__bondPosition___datePicker"
            },
            {
                "component": "module",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "44e36062d7313251c985ca3dccd27415",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "盘中个券异动详情Module",
                "orderNo": null,
                "parentModule": null,
                "pid": "b9bc5b7e5fc7ebe43e5f0b68b9e79f9e",
                "showStatus": 1,
                "sn": "_information_priceChanges__Module___couponIntraday",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_information_priceChanges__Module___couponIntraday"
            },
            {
                "component": "menu",
                "createTime": 1644389443000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "4729349c2a248199abe04076e5a11802",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "产品",
                "orderNo": null,
                "parentModule": null,
                "pid": null,
                "showStatus": 1,
                "sn": "production",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "4c8ec2398e2b9b34a6f86bdd47b1880d",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "渠道分布",
                "orderNo": null,
                "parentModule": null,
                "pid": "c76b858f5cc0f54680c73efbc0e7d652",
                "showStatus": 1,
                "sn": "_marketing_channelDistribution",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_channelDistribution"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "4c9321bd8be7204dd7e214261ee6020d",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "我的MOT待办",
                "orderNo": null,
                "parentModule": null,
                "pid": "39035fe22e4e75cafdcc7c21d92636f2",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM_myMotTask",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM_myMotTask"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "4eedebbc846f5d5fdaf48dd332673e98",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "开户信息管理",
                "orderNo": null,
                "parentModule": null,
                "pid": "f813036a04478603f4e30019e71d3823",
                "showStatus": 1,
                "sn": "/production/businessManage/messageManage",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/businessManage/messageManage"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "5032f6a4edca3e3970c6073b570e9450",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "用户信息",
                "orderNo": null,
                "parentModule": null,
                "pid": "8e2c713e7ab9883cf6e00d18bf098380",
                "showStatus": 1,
                "sn": "_marketing_fundsalesmrksupport_userInfo",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_fundsalesmrksupport_userInfo"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "50f484d9b3bb351deefa79ec558eb36f",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "筛选推送审核",
                "orderNo": null,
                "parentModule": null,
                "pid": "26d4210f79a49b9e70aa9c6cab20caa5",
                "showStatus": 1,
                "sn": "/industrialChain/set/movePush",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/industrialChain/set/movePush"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "5261b92bc9077df22864b4ad8cd50135",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "销售监控大盘",
                "orderNo": null,
                "parentModule": null,
                "pid": "c76b858f5cc0f54680c73efbc0e7d652",
                "showStatus": 1,
                "sn": "_marketing_marketing_mainPage",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_marketing_mainPage"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "541c5c865aeaf2193ee4511a7184c372",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "基金产品",
                "orderNo": null,
                "parentModule": null,
                "pid": "c76b858f5cc0f54680c73efbc0e7d652",
                "showStatus": 1,
                "sn": "_marketing_product",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_product"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "54da5c52abb63fc4091aadbe80d28e59",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "客户查询",
                "orderNo": null,
                "parentModule": null,
                "pid": "39035fe22e4e75cafdcc7c21d92636f2",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM_customerQuery",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM_customerQuery"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "5790659b182ea9a06ad7a17931886f6c",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "我的客户",
                "orderNo": null,
                "parentModule": null,
                "pid": "39035fe22e4e75cafdcc7c21d92636f2",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM_myCustomers",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM_myCustomers"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "5939df08115b7806e97c3a93bb65cc48",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "公司获奖page",
                "orderNo": null,
                "parentModule": null,
                "pid": "c48cdfe3dd6ea64e852b8749af96a9d1",
                "showStatus": 1,
                "sn": "_production_FundCompany__Menu___authAward",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_FundCompany__Menu___authAward"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "595199383a98bcc4ee439cbed27ae1fb",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "MOT事件触发结果",
                "orderNo": null,
                "parentModule": null,
                "pid": "39035fe22e4e75cafdcc7c21d92636f2",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM_motTriggerResult",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM_motTriggerResult"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "5d1958cd9c172a88b3d77beec81066ce",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "筛选推送审核page",
                "orderNo": null,
                "parentModule": null,
                "pid": "50f484d9b3bb351deefa79ec558eb36f",
                "showStatus": 1,
                "sn": "_industrialChain_Set__Menu___MovePush",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_industrialChain_Set__Menu___MovePush"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "6732bb39e7e5902c6a920e108dac3fce",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "机构服务客户配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_consumer",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_consumer"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "6deac759fbe371560dfd623e47ecf56f",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "尾佣管理page",
                "orderNo": null,
                "parentModule": null,
                "pid": "2ae999ece8c5160b476d33f0371bc3f9",
                "showStatus": 1,
                "sn": "_Production_Menu__TrailingCommission",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_Production_Menu__TrailingCommission"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "71acb33385da6fe90b75856ce7b12f92",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "终止日报告",
                "orderNo": null,
                "parentModule": null,
                "pid": "4729349c2a248199abe04076e5a11802",
                "showStatus": 1,
                "sn": "/production/endDate",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/endDate"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "745f0117c88c42c8b9d654b9c971628c",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "考核目标配置页面",
                "orderNo": null,
                "parentModule": null,
                "pid": "a431b482cd7f0a1c36a150382230be3b",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_vogTarget",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_vogTarget"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "78fd1c7a280152547c622fc259b2410d",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "产品筛选我的客户",
                "orderNo": null,
                "parentModule": null,
                "pid": "39035fe22e4e75cafdcc7c21d92636f2",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM_filterMyCustomers",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM_filterMyCustomers"
            },
            {
                "component": "button",
                "createTime": 1644977327000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "7a4953ef7b970778f40793782eab5968",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "指数使用费新增button",
                "orderNo": null,
                "parentModule": null,
                "pid": "8d72b816ca257f18611dc57cf662e194",
                "showStatus": 1,
                "sn": "_production_indexFee__singleTable___createButton",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_indexFee__singleTable___createButton"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "8448b19ff588a0318031b2af78c5e85c",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "客户查询日志",
                "orderNo": null,
                "parentModule": null,
                "pid": "39035fe22e4e75cafdcc7c21d92636f2",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM_accessLog_customerQueryLog",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM_accessLog_customerQueryLog"
            },
            {
                "component": "investment_system_admin",
                "createTime": 1659675026000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "851e9515692b529ed3741543794c09af",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "投资系统管理员",
                "orderNo": null,
                "parentModule": null,
                "pid": "56bf1c18be6f3a70b32e86359e8c2f90",
                "showStatus": 1,
                "sn": "investment_system_admin",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "investment_system_admin"
            },
            {
                "component": "element",
                "createTime": 1650441083000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "86961d0ecde239681d42bd3a9c6ec37a",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "持仓信息十大股票时间信息",
                "orderNo": null,
                "parentModule": null,
                "pid": "d4d7a66aa11d9c994c56cf62ef0a06f3",
                "showStatus": 1,
                "sn": "_production_index_detail__stockPosition___datePicker",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_index_detail__stockPosition___datePicker"
            },
            {
                "component": "page",
                "createTime": 1663901353000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "86af9d70a27378d95ab738f7738c2e76",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "基础配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "8e2c713e7ab9883cf6e00d18bf098380",
                "showStatus": 1,
                "sn": "_marketing_fundsalesmrksupport",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_fundsalesmrksupport"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "8cda7d39e97ad85b314236e8e5915a48",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "渠道类型配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_agency",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_agency"
            },
            {
                "component": "card",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "8d72b816ca257f18611dc57cf662e194",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "指数使用费card",
                "orderNo": null,
                "parentModule": null,
                "pid": "302cb20d253e7992b5bf8ba8423039a2",
                "showStatus": 1,
                "sn": "_production_indexFee__singleTable",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_indexFee__singleTable"
            },
            {
                "component": "menu",
                "createTime": 1663896531000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "8e2c713e7ab9883cf6e00d18bf098380",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "理财师后台配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "fundsalesmrksupport",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "fundsalesmrksupport"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "957a9f84ab2374d2cf808bf0dec324db",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "客户归属",
                "orderNo": null,
                "parentModule": null,
                "pid": "39035fe22e4e75cafdcc7c21d92636f2",
                "showStatus": 1,
                "sn": "_marketing_advisorCRM_customerBelongTo",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_advisorCRM_customerBelongTo"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "98bf3f13af1009bd6001475b91457dcc",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "销售VOG看板",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_vogBoard",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_vogBoard"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "9c89557f5aeb0eb929ced283a8d7210c",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "机构客户配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_customer",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_customer"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "a3d7e1ce47b0b635fb36b97e44f032c7",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "字典数据配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_dict",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_dict"
            },
            {
                "component": "module",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "a3fc3a7b2ee55814b31c441e47191557",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "盘后个券异动详情",
                "orderNo": null,
                "parentModule": null,
                "pid": "b9bc5b7e5fc7ebe43e5f0b68b9e79f9e",
                "showStatus": 1,
                "sn": "_information_priceChanges__Module___couponAfter",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_information_priceChanges__Module___couponAfter"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "a431b482cd7f0a1c36a150382230be3b",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "销售后台配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "salesConfig",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "salesConfig"
            },
            {
                "component": "page",
                "createTime": 1652671819000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "ab6e002ef1481c9ff9623afe80924da5",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "产品类型配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_fund",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_fund"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "ad811c131918282ae5686e257878a8a3",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "基金索引",
                "orderNo": null,
                "parentModule": null,
                "pid": "9dc4329960fd3ac082eb2bdc8023f541",
                "showStatus": 1,
                "sn": "/production/summary/hotFundIndex/_single_",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/summary/hotFundIndex/_single_"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "b1941714b01248fbfd3ca6d4d18037dd",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "基金宣推数据page",
                "orderNo": null,
                "parentModule": null,
                "pid": "25bd5f5f50990bac3df8a67557caaa05",
                "showStatus": 1,
                "sn": "_production_IndexDetail__Menu___Promote",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_IndexDetail__Menu___Promote"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "b58ce3f0c8953d1dc3071ae7e163fbcd",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "开户信息管理page",
                "orderNo": null,
                "parentModule": null,
                "pid": "4eedebbc846f5d5fdaf48dd332673e98",
                "showStatus": 1,
                "sn": "_production_businessManage__messageManage",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_businessManage__messageManage"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "ba9bad34d77e05a12d22ca66fe9af23e",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "产业链",
                "orderNo": null,
                "parentModule": null,
                "pid": null,
                "showStatus": 1,
                "sn": "/industrialChain",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/industrialChain"
            },
            {
                "component": "menu",
                "createTime": 1662514048000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "c48cdfe3dd6ea64e852b8749af96a9d1",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "基金公司",
                "orderNo": null,
                "parentModule": null,
                "pid": "4729349c2a248199abe04076e5a11802",
                "showStatus": 1,
                "sn": "/production/FundCompany",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/FundCompany"
            },
            {
                "component": "menu",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "c76b858f5cc0f54680c73efbc0e7d652",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "看板类",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "salesBoard",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "salesBoard"
            },
            {
                "component": "button",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "c86842f281e7b34f2192caa9acec6a4f",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "基金索引列项筛选项Button",
                "orderNo": null,
                "parentModule": null,
                "pid": "ad811c131918282ae5686e257878a8a3",
                "showStatus": 1,
                "sn": "__production_hotFundIndex__tagManage___editButton",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "__production_hotFundIndex__tagManage___editButton"
            },
            {
                "component": "menu",
                "createTime": 1644389442000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "c90481c08033f40d1338db706e2af50a",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "指数",
                "orderNo": null,
                "parentModule": null,
                "pid": "4729349c2a248199abe04076e5a11802",
                "showStatus": 1,
                "sn": "index",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/production/index"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "cabbfa66e93887dd86557ffe69765e8f",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "区域考核配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_dataConfig_bankRegion",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_dataConfig_bankRegion"
            },
            {
                "component": "page",
                "createTime": 1662514208000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "da09efe0058a4ae2790d7c2de5a33a32",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "公司持有人",
                "orderNo": null,
                "parentModule": null,
                "pid": "c48cdfe3dd6ea64e852b8749af96a9d1",
                "showStatus": 1,
                "sn": "_production_FundCompany__Menu___Holder",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_FundCompany__Menu___Holder"
            },
            {
                "component": "menu",
                "createTime": 1662104946000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "dfbb8db89a54f76279efaf655ea157d1",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "销售",
                "orderNo": null,
                "parentModule": null,
                "pid": null,
                "showStatus": 1,
                "sn": "sales",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "/sales"
            },
            {
                "component": "page",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "ea572ee93d50ae99af65ca5bba2af69c",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "机构服务观点配置",
                "orderNo": null,
                "parentModule": null,
                "pid": "dfbb8db89a54f76279efaf655ea157d1",
                "showStatus": 1,
                "sn": "_marketing_viewpoint",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_marketing_viewpoint"
            },
            {
                "component": "module",
                "createTime": 1669104923000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "ee7e3316b7e769deb6202bd88b737d68",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "股票详情Module",
                "orderNo": null,
                "parentModule": null,
                "pid": "b9bc5b7e5fc7ebe43e5f0b68b9e79f9e",
                "showStatus": 1,
                "sn": "_information_priceChanges__Module___stockDetail",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_information_priceChanges__Module___stockDetail"
            },
            {
                "component": "button",
                "createTime": null,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "f68394e1e90487aee0022bac4da9e677",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "TA参数表新增编辑权限",
                "orderNo": null,
                "parentModule": null,
                "pid": "fc2731bb1fe8f5dd0752cf6df1b1ae6a",
                "showStatus": 1,
                "sn": "_production_parameter_table__operations",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "_production_parameter_table__operations"
            },
            {
                "component": "menu",
                "createTime": 1663063891000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "0663ff9be143335695f71ca23bb4e70b",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_report1663059444025.png",
                "keyword": null,
                "moduleType": 0,
                "name": "代销持营报告",
                "orderNo": 1,
                "parentModule": null,
                "pid": "cf2ac6e675e54c984b5bbe2f0f973288",
                "showStatus": 1,
                "sn": "/fundsalescrm_mobile_sc_product",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663063951000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "6beb2f051bddb76f21ad8e1b3921538a",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_online1663059449423.png",
                "keyword": null,
                "moduleType": 0,
                "name": "渠道上线情况",
                "orderNo": 1,
                "parentModule": null,
                "pid": "f8fa129985503e016f9cdfaafc63bdf2",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_online",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663115807000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "fe2677694a5e9760271885686ddd1d7c",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_sale_kanban1662622244305.png",
                "keyword": null,
                "moduleType": 0,
                "name": "销售看板",
                "orderNo": 1,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_sale_kanban",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "dingtalk://dingtalkclient/action/open_micro_app?pVersion=1&packageType=1&&miniAppId=5000000002227284&corpId=ding1a99b5692ec21666acaaa37764f94726&agentId=1475369533"
            },
            {
                "component": "menu",
                "createTime": 1662623829000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "4ab4071391d0774b744fb5872bcd2ac2",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_sc_customer1662622253478.png",
                "keyword": null,
                "moduleType": 0,
                "name": "客户查询",
                "orderNo": 2,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_sc_customer",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663116009000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "b1ac253f2d078d1cd74a95fb01604d0a",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_sc_product1662622255341.png",
                "keyword": null,
                "moduleType": 0,
                "name": "产品查询",
                "orderNo": 3,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_sc_product",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663116489000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "4f682d07a163fb1ef3dc3daeec4626c2",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_sc_work_report1662622257375.png",
                "keyword": null,
                "moduleType": 0,
                "name": "工作日报",
                "orderNo": 4,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_sc_work_report",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663116471000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "dbae365d7088cde8f91768c377f3da65",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_sc_central_intelligence1662622249351.png",
                "keyword": null,
                "moduleType": 0,
                "name": "情报中心",
                "orderNo": 5,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_sc_central_intelligence",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663115994000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "3b6cd2a9fb19da505a4a5fe9f0295666",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_sc_cockpit1662622251384.png",
                "keyword": null,
                "moduleType": 0,
                "name": "驾驶舱",
                "orderNo": 6,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 0,
                "sn": "fundsalescrm_mobile_sc_cockpit",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663115930000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "c6b4f4033d50d11069090df93adf0008",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_davinci1662622222194.png",
                "keyword": null,
                "moduleType": 0,
                "name": "达芬奇",
                "orderNo": 7,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 0,
                "sn": "fundsalescrm_mobile_davinci",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "menu",
                "createTime": 1663064491000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "e9c25f1c07b6e53c840f2b651beae10a",
                "image": "https://cdnprod.tianhongjijin.com.cn/thfile/fundsalescrm_mobile_honorhall1662622238145.png",
                "keyword": null,
                "moduleType": 0,
                "name": "荣誉堂",
                "orderNo": 8,
                "parentModule": null,
                "pid": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_honorhall",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": "dingtalk://dingtalkclient/action/open_micro_app?pVersion=1&packageType=1&&miniAppId=5000000002714405&corpId=ding1a99b5692ec21666acaaa37764f94726&agentId=1682077959"
            },
            {
                "component": "group",
                "createTime": 1664287675000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "4cdbe2446be3f4bbca3ea9f12f102ae6",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "功能列表",
                "orderNo": 11,
                "parentModule": null,
                "pid": "11dc9625c6562fb9f1ff1d2ab16abcfb",
                "showStatus": 1,
                "sn": "fundsalescrm_mobile_group_3",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "group",
                "createTime": 1663837847000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "cf2ac6e675e54c984b5bbe2f0f973288",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "达芬奇(关键报表)",
                "orderNo": 12,
                "parentModule": null,
                "pid": "11dc9625c6562fb9f1ff1d2ab16abcfb",
                "showStatus": 0,
                "sn": "fundsalescrm_mobile_group_4",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            },
            {
                "component": "group",
                "createTime": 1664432727000,
                "creator": null,
                "delFlag": 1,
                "extraInfo": null,
                "id": "f8fa129985503e016f9cdfaafc63bdf2",
                "image": null,
                "keyword": null,
                "moduleType": 0,
                "name": "渠道合作",
                "orderNo": 13,
                "parentModule": null,
                "pid": "11dc9625c6562fb9f1ff1d2ab16abcfb",
                "showStatus": 0,
                "sn": "fundsalescrm_mobile_group_5",
                "state": 15,
                "status": 1,
                "subModules": null,
                "updateTime": null,
                "updator": null,
                "url": ""
            }
        ],
        "realName": "ssoadmin01",
        "updateTime": 1675908337000,
        "updator": null,
        "userName": "ssoadmin01",
        "userNo": "0000"
    },
    "errorCode": null,
    "errorContext": null,
    "errorMsg": null,
    "redirectUrl": null,
    "showType": null,
    "success": true
};

  return {
    settings: {},
    tabLayoutType: 'multi',
    userName: data?.userName || '',
    userNo: data?.userNo || '',
    moduleVOS: data?.moduleVOS || [],
    appPrivilegeValueVOS: data?.appPrivilegeValueVOS || [],
    aclvoList: data?.aclvoList || [],
    compareIndexes: [],
    realName: data?.realName || '',
  };
}

// const codeMessage = {
//   200: '服务器成功返回请求的数据。',
//   201: '新建或修改数据成功。',
//   202: '一个请求已经进入后台排队（异步任务）。',
//   204: '删除数据成功。',
//   400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
//   401: '用户没有权限（令牌、用户名、密码错误）。',
//   403: '用户得到授权，但是访问是被禁止的。',
//   404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
//   405: '请求方法不被允许。',
//   406: '请求的格式不可得。',
//   410: '请求的资源被永久删除，且不会再得到的。',
//   422: '当创建一个对象时，发生一个验证错误。',
//   500: '服务器发生错误，请检查服务器。',
//   502: '网关错误。',
//   503: '服务不可用，服务器暂时过载或维护。',
//   504: '网关超时。',
// };

/**
 * 异常处理程序
 */
const errorHandler = (error: ResponseError) => {
  const { response }: { response: any } = error;
  const { showType, errorMsg, errorCode, redirectUrl } = response || {};

  if (errorCode === '302') return response || {};

  if (showType === '0') return response || {};

  if (showType === '9') location.href = redirectUrl;

  if (showType === '1') {
    notification.error({
      message: '',
      description: errorMsg,
    });
    return response;
  }

  if (showType === '4') {
    message.error(errorMsg);
    return response;
  }

  if (errorCode && errorMsg) {
    message.warning(errorMsg);
  } else {
    message.warning('接口异常，请稍后重试');
  }

  return response || {};
};

export const request: RequestConfig = {
  requestInterceptors: [
    (_, options) => {
      return {
        options: {
          ...options,
          headers: {
            ...(options?.headers ?? {}),
            'redirect-url': window.location.href,
          },
        },
      };
    },
  ],
  middlewares: [
    async function middlewareAuth(ctx, next) {
      await next();

      if (ctx.res && ctx.res.success) {
        return;
      }

      if (ctx.res && !ctx.res.success && ctx.res.redirectAddr) {
        window.location.href = ctx.res.redirectAddr;
      }

      // 登录异常
      // if (
      //   !success &&
      //   errorCode === 'TE0311001402' &&
      //   reqUrl !== '/login' &&
      //   location?.pathname !== '/login'
      // ) {
      //   const hashStr = window.location.hash;
      //   const hashStrs = hashStr.split('#/');

      //   if (history && hashStrs.length === 2)
      //     history.push(`/login?redirectUrl=${encodeURIComponent(hashStrs[1])}`);
      //   // message.warn('登录已失效，请重新登录');
      // }
    },
  ],
  errorHandler,
};

export const qiankun = new Promise((resolve) => {
  setTimeout(() => {
    resolve({
      apps: [
        {
          name: 'data_browser',
          entry: _QIANKUN_ENTRY_CONFIG._DATA_BROWSER,
          credentials: true,
        },
        {
          name: 'oper_mng',
          entry: _QIANKUN_ENTRY_CONFIG._OPER_MNG,
          credential: true,
        },
        {
          name: 'industry_chaincore',
          entry: _QIANKUN_ENTRY_CONFIG._INDUSTRY_CHAINCORE,
          credentials: true,
        },
      ],
      sandbox: {
        strictStyleIsolation: true,
      },
    });
  }, 500);
}).then(({ apps, sandbox }: any) => ({
  apps,
  sandbox,
}));

// let extraRoute: any;

// export function patchRoutes({ routes }) {
//   routes.forEach((r) => {
//     if (r.path === '/') {
//       r?.routes?.unshift(extraRoute);
//     }
//   });
// }

// export function render(oldRender) {
//   Promise.resolve({
//     path: '/data_browser',
//     name: '数据魔方',
//     microApp: 'data_browser',
//     routes: [
//       {
//         path: '/index',
//         name: '数据浏览器',
//       },
//     ],
//   }).then((res) => {
//     extraRoute = res;
//     oldRender();
//   });
// }
